### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by GilsonJReis** [RobertMyles/cepR#10]
Olá,
Utilizei o script de artigo que que utiliza a biblioteca cepR:

#cria um data frame temporário que será utilizado para ser preenchido durante as iterações relativas a cada CEP.
geo_coded<- data.frame(estado=character(),cidade=character
bairro=character(),cep=character(),logradouro=character(),latitude=character(),longitude=character(),altitude=character(),ddd=character(),cod_IBGE=character(),quality = logical(),cep_buscado = character(),stringsAsFactors=FALSE)
cep_unico <- as.character(unique(internacoes$CEP)) # cria um vetor com os CEPS sem repetição para minimizar a realização das consultas na API do CEP Aberto
#Loop de consulta de cada CEP listado no vetor: cep_unico
for (i in 1:10000) {
sys1 <- Sys.time()
consulta <-busca_cep(cep=(cep_unico[[i]]), token= ‘seu token’)
consulta$quality <- anyNA(c(consulta$latitude, consulta$longitude))
consulta$cep_buscado <- cep_unicos[[i]]
geo_coded <- rbind(geo_coded, consulta, make.row.names=FALSE)
if(Sys.time()-sys1 <=4.0) Sys.sleep(4.0-(Sys.time()-sys1))}

Consegui fazer consultas que foram muito úteis, mas na última semana a busca começa e depois  ocorre o seguinte erro:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - O certificado recebido expirou.

Você pode me ajudar?

Desde já agradeço.

**Comment by RobertMyles** [comment]
Olá, 
Esse erro vem de curl e não de cepR, e ao melhor do meu conhecimento é vinculado com máquinas de Windows. Você está utilizando computador atrás VPN (de trabalho etc)? Uma outro coisa pode ser que o certificado do website cepaberto está inválido. Neste caso, seria melhor contatar o equipe do cepaberto mesmo.
Também, se você está utilizando o cepR muito (10000 vezes), por favor apoia o projecto.
