### ISSUE TITLE
Update cepR to new Version API V3

### ISSUE THREAD

**Issue by ragapack** [RobertMyles/cepR#4]
Hi,
I tested your Package cepR, works fine for me but in the Code I saw you are using the older API V2.
There is an new API V3, can you update your Package ?
http://cepaberto.com/api_key
Thank you

**Comment by RobertMyles** [comment]
Thanks for the heads up, @ragapack ! I'm in the middle of upgrading the package to use the new API. See the 'dev' branch if you want to try it out.
