### ISSUE TITLE
Error: "Error: Can't pluck from a externalptr"

### ISSUE THREAD

**Issue by jocamarada** [RobertMyles/cepR#5]
While running the code below:

```
library(cepR)
token = "XXXXXXXXXXXXX"
Est_MA <- busca_estado(estado = "MA", token = token)
```
I get the following error:

`Error: Can't pluck from a externalptr`

**Comment by RobertMyles** [comment]
cepR is currently out of date with the CEPAberto API (v2 vs v3). I'll update it ASAP, or feel free to make a PR if you'd like.
