### ISSUE TITLE
Update to v3

### ISSUE THREAD

**Issue by RobertMyles** [RobertMyles/cepR#6]

**Comment by RobertMyles** [comment]
Seems there is an API issue. Running the code from the site examples gives me:

```r
GET("http://www.cepaberto.com/api/v3/address?estado=SP&cidade=Ubatuba",
  add_headers(Authorization = auth)) %>% 
  content("parsed")
```
Result:
```r
named list()
```

This is not an R issue. Copying directly from the site:

```python
import requests

url = "http://www.cepaberto.com/api/v3/address"
headers = {'Authorization': 'Token token=XXXXXXXXXX'}
params = {'estado': 'SP', 'cidade': 'Ubatuba'}
response = requests.get(url, headers=headers, params=params)
print(response.json())
```
Result:
```python
{}
```

**Comment by RobertMyles** [comment]
@edumucelli do we need lat & lng for estado/cidade requests, Eduardo?

```r
GET("http://www.cepaberto.com/api/v3/nearest?cidade=Ubatuba&estado=SP", add_headers(Authorization = auth)) %>% content("parsed")
$message
[1] "Atributos \"lat\" e \"lng\" necessários"
```

**Comment by edumucelli** [comment]
`nearest` only takes `lat` and `lng`. The semantic behind it is that it will find the nearby CEPs from a point centered on this very coordinate formed by the `lat` and `lng`.

I could indeed make it accept a `cidade` and `estado` but I have not thought about it beforehand.

**Comment by RobertMyles** [comment]
Ah, understood, my mistake, I was confusing it with the cidade/estado request.

**Comment by RobertMyles** [comment]
Closing, CRAN submission underway.
